### ISSUE TITLE
Support for Nomad

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-hcl#116]
Formatting would be great. I installed this extension because its description says:

> This extension provides [HCL](https://github.com/hashicorp/hcl#hcl) syntax highlighting for files that use .hcl as the file extension, for example:
> 
> [Nomad job specification](https://www.nomadproject.io/docs/job-specification/hcl2)
> [Packer template](https://www.packer.io/docs/templates/hcl_templates)
> [Waypoint project](https://www.waypointproject.io/docs/waypoint-hcl)

I thought this would include formatting as well, specifically for `*.nomad` files.

_Originally posted by @pikeas in https://github.com/hashicorp/vscode-hcl/issues/98#issuecomment-1152991770_

**Comment by radeksimko** [comment]
> I thought this would include formatting as well, specifically for *.nomad files.

You are right that Nomad documentation uses the `*.nomad` naming convention, but this is currently purely a convention, unlike in Packer, Waypoint or Terraform since Nomad jobs are addressed by the full filename/path in `nomad job run <JOB_SPEC_PATH>`.

There are conversations about loading multiple jobs in https://github.com/hashicorp/nomad/issues/7954 which would then necessitate a naming convention to be strictly followed.

In the meantime there is nothing preventing you from naming your job files `*.nmd.hcl`, which is a naming convention similar to the Packer one (`*.pkr.hcl` & `*.pkrvars.hcl`).

I'll see if we could (re)establish that naming convention with `.hcl` suffix even before committing to one becomes necessary - I don't see why we couldn't do it, but I will need to talk to the Nomad team which of course owns the docs.

Alternatively we could either publish Nomad extension in some form and shape or consider adding that old convention to this one.

**Comment by pikeas** [comment]
Not to overly bikeshed, but how about `*.nmd.hcl`?

**Comment by radeksimko** [comment]
@pikeas That sounds like a suggestion for the Nomad team in the linked issue. For the purposes of decent editor experience, I'm fine with `*.anything.hcl` as long as the `anything` part is unique and consistent.

**Comment by daledude** [comment]
I'm confused by the push back to simply handling .nomad like .hcl. The .nomad file extension has been suggested, documented, blogged about and used for many years. Must be a technical issue I'm missing?

**Comment by radeksimko** [comment]
@daledude There is a few motivations behind the push back:
 - this is _HCL_ extension, rather than _Nomad_ extension, and hence we'd love to keep it focused on the bare-bones HCL, rather than flavours of it
 - VS Code doesn't handle conflicts well e.g. when two extensions attempt to highlight the same file because they both claim the same file, so we want to avoid conflicts as much as we can

One option we may consider however is releasing a separate simple/MVP Nomad extension which simply maps `*.nomad` (and later `*.nomad.hcl`) to the grammar we already have. Maintaining that technical debt within that separate extension seems acceptable to me.

**Comment by calebschoepp** [comment]
Is there a fix around this? Trying to get my `.nomad` files highlighted.

**Comment by radeksimko** [comment]
Nomad now recommends `*.nomad.hcl` as per https://github.com/hashicorp/nomad/pull/15997 which should be part of the next release. Job spec filenames were always recommendations, which were not enforced in any way by Nomad (unlike e.g. `*.tf` files by Terraform), given that one has to specify exact path e.g. in `nomad job run ./path/to/job-spec`.

With that in mind, folks should feel free to rename those files, i.e. append `.hcl` to existing `*.nomad` filenames, to have those files claimed by the HCL extension.

**Comment by calebschoepp** [comment]
Got it. For anyone who isn't able to change the file extensions because they don't own the code I found a workaround.

You can just force VS Code to treat `.nomad` files as `.hcl` files. https://stackoverflow.com/questions/29973619/how-to-make-vs-code-treat-a-file-extensions-as-a-certain-language/51228725#51228725

**Comment by aleneum** [comment]
Just FYI for people coming here from Google/Bing/etc:

Today, I was also looking for a way to format `nomad.hcl` files with vscode and realised that nomad (v1.5.3) comes with a format method `nomad fmt <path_to_file>`. So I made a custom formatting function with the help of [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) and added the following to my `.vscode/settings.json`:

```json
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.nomad\\.hcl",
        "cmd": "nomad fmt ${file}"
      }
    ]
  }
}
```

Now my job files are formatted every time I save them.
