### ISSUE TITLE
Support HCL for Gitlab Web IDE

### ISSUE THREAD

**Issue by mehdiMj-ir** [hashicorp/vscode-hcl#271]
Is there any chance for supporting `hcl`  extension on **Gitlab Web IDE**?

**Comment by radeksimko** [comment]
Hi @mehdiMj-ir 
As far as I can tell, the GitLab Web IDE is based on VS Code, so the HCL extension should already be compatible.

The question is of course _how_ can one install it. According to https://gitlab.com/gitlab-org/gitlab/-/issues/407455 it seems that GitLab does not allow Marketplace-based installations at this point. I'm not aware of them maintaining another Marketplace of their own.

As the help page also mentions, the only way of installing any extension is to manually load the vsix file. While we don't publish it explicitly, it is available for download from the VSCode Marketplace:

https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL
<img width="308" alt="Screenshot 2023-09-20 at 09 15 34" src="https://github.com/hashicorp/vscode-hcl/assets/287584/015dc6ac-1753-4d5a-aeb6-a6aeca892d4a">

In terms of longer-term my own personal guess is that GitLab will avoid the official Marketplace for legal/licensing reasons. In case they go with open-vsx.org though, [we publish our extension there as well](https://open-vsx.org/extension/hashicorp/hcl), so it should work out of the box in such a scenario.

How they will actually let users discover and install extensions though is more up to GitLab, so there is nothing more we can do on our end at this point from what I can tell.
